name: ci
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade pip setuptools
      - run: pip install .
      - name: Test import modules
        run: |
          cd # Change directory to ensure we do not load the source module
          python -c 'import apt.eigen_wrapper; help(apt.eigen_wrapper)'
